"""
Reader for the upstream speech_regions.parquet (oracle voice activity, word-merged
at gap 0.25 s). This is the SINGLE source of speaker activity for BOTH the timing
features and the five VA-baseline features, so model activity and baseline activity
never diverge.

Expected schema (one row per merged region):
    meeting_id : str
    speaker    : str   (A/B/C/D/E -- the AMI nxt_agent letter)
    start      : float (seconds)
    end        : float (seconds)
A `gap` column may be present (ignored). Onset/offset column names start/end are
also accepted as onset/offset.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import pandas as pd

Region = Tuple[float, float]


class SpeechRegions:
    def __init__(self, parquet_path: str):
        self.path = Path(parquet_path)
        if not self.path.exists():
            raise FileNotFoundError(
                f"speech_regions not found: {self.path}. It is produced upstream "
                "(groupturn_labeler); for development a fixture is generated by "
                "tests/build_fixture.py."
            )
        df = pd.read_parquet(self.path)
        cols = {c.lower(): c for c in df.columns}
        s_col = cols.get("start") or cols.get("onset")
        e_col = cols.get("end") or cols.get("offset")
        m_col = cols.get("meeting_id") or cols.get("meeting")
        sp_col = cols.get("speaker") or cols.get("spk")
        if not all([s_col, e_col, m_col, sp_col]):
            raise ValueError(f"speech_regions missing required columns; got {list(df.columns)}")
        self._by_key: Dict[Tuple[str, str], List[Region]] = defaultdict(list)
        for m, sp, s, e in zip(df[m_col], df[sp_col], df[s_col], df[e_col]):
            self._by_key[(str(m), str(sp))].append((float(s), float(e)))
        for k in self._by_key:
            self._by_key[k].sort()

    def regions(self, meeting_id: str, speaker: str) -> List[Region]:
        return list(self._by_key.get((meeting_id, speaker), []))

    def regions_before(self, meeting_id: str, speaker: str, t: float) -> List[Region]:
        """Regions that STARTED before t (onset < t); may extend past t (ongoing)."""
        return [(s, e) for (s, e) in self._by_key.get((meeting_id, speaker), []) if s < t]

    def human_regions_before(
        self, meeting_id: str, human_speakers: Sequence[str], t: float
    ) -> Dict[str, List[Region]]:
        return {sp: self.regions_before(meeting_id, sp, t) for sp in human_speakers}
